# Generated by Django 3.2.4 on 2021-06-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_range", models.CharField(max_length=255)),
                ("resolution", models.CharField(max_length=255)),
                ("sampling", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LightSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_type", models.CharField(max_length=255)),
                ("wavelength", models.CharField(max_length=255)),
                ("temperature", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="spectraldata",
            name="crop",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="main.crop"
            ),
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="device",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="main.device"
            ),
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="region",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="main.region"
            ),
        ),
    ]
