# Generated by Django 3.2.4 on 2021-06-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_device_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spectraldata",
            options={
                "verbose_name": "Spectral data",
                "verbose_name_plural": "Spectral data",
            },
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="intensity",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="registered_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="spectraldata",
            name="wavelength",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="spectraldata",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.crop",
            ),
        ),
        migrations.AlterField(
            model_name="spectraldata",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.device",
            ),
        ),
        migrations.AlterField(
            model_name="spectraldata",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.region",
            ),
        ),
    ]
