# Generated by Django 3.2.4 on 2021-06-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20210614_2148"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectraldata",
            name="set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.set",
            ),
        ),
    ]
