# Generated by Django 3.2.4 on 2021-06-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_spectraldata_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectraldata",
            name="light_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.lightsource",
            ),
        ),
    ]
